### ISSUE TITLE
[BUG] Not all standard keywords are supported for syntax highlighting

### ISSUE THREAD

**Issue by GlenNicholls** [Bochlin/rust_hdl_vscode#4]
Almost all keywords are supported, however types in the standard ieee libraries are not. Things like `std_logic`, `std_logic_vector`, `real`, `unsigned`, etc. should all be supported. IMO, these should be a different color than the currently supported keywords

**Comment by GlenNicholls** [comment]
There should also be `failure`, `warning`, `error`, and `note`.

**Comment by Bochlin** [comment]
Added syntax from textmate bundle in 9e19ed61aa8f4e75daad242226ff3b3c4703dc51
